name = "manage-mbgue"
main = "src/api/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mbg-database"
database_id = "ed7a9b5f-12fa-4ddf-a5a1-e9fdea79ac97"

[site]
bucket = "./dist"
